[workspace]

members = [
        "sypytkowski-convergent",
        "convergent-experiment",
        "convergent-experiment-protocol-gen",
        "convergent-experiment-protocol",
        "convergent-experiment-ws",
        "sypytkowski-commutative",
]
