[workspace]

members = [
        "sypytkowski-blog",
        "convergent-experiment",
        "convergent-experiment-protocol-gen",
        "convergent-experiment-protocol",
        "convergent-experiment-ws"
]
